// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.bookstore.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;
import com.xhb.core.response.HttpResponseData;

public class CheckResp extends HttpResponseData {

	private boolean found;
	private long price;

	public CheckResp() {
	}

	public CheckResp(boolean found, long price) {
		this.found = found;
		this.price = price;
	}

	public boolean isFound() {
		return this.found;
	}

	public void setFound(boolean found) {
		this.found = found;
	}

	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

}
