// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.bookstore.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.packet.HttpData;
import com.xhb.core.response.HttpResponseData;

public class CheckReq extends HttpData {

	private String book = "";

	public CheckReq() {
	}

	public CheckReq(String book) {
		this.book = book;
	}

	@NotNull 
	public String getBook() {
		return this.book;
	}

	public void setBook(@NotNull String book) {
		this.book = book;
	}

}
